import pandas as pd
import generate_data as data


def create_table(rows):
    """
    Create the table
    :param rows: Number of rows
    :return: none
    """
    table = pd.DataFrame()
    ids = set()
    eci_ids = set()
    list_id = []
    eci_nums = []
    names = []
    genders = []
    last_names = []
    p_mails = []
    a_mails = []
    roles = []
    cells = []
    bloods = []
    births = []
    ages = []
    atts = []
    cell_at = []
    mail_at = []
    degrees = []
    costs = []
    strats = []
    enroles = []
    t_avg = []
    p_avg = []
    states = []
    progs = []
    plans = []
    adds = []
    ctys = []
    sems = []
    p_cred = []
    pens = []
    fins = []
    fins_e = []
    fams = []
    eng_lvls = []
    type_docs = []
    epss = []
    total_creds = []
    ap_creds = []
    l_creds = []
    ac_creds = []
    armys = []
    allys = []
    debts = []
    portal_ids = []
    cancell = []
    failed_set = []
    exp_years = []
    countries = []
    b_cities = []
    c_states = []
    monits = []
    for i in range(rows):
        list_id += [data.id_num(ids)]
        eci_nums += [data.eci_number(eci_ids)]
        genders += [data.gender()]
        names += [data.name(genders[i])]
        last_names += [data.last_name()]
        births += [data.birth(list_id[i])]
        ages += [data.age(births[i])]
        p_mails += [data.personal_mail(names[i], last_names[i])]
        roles += [data.rol(ages[i])]
        a_mails += [data.eci_mail(names[i], last_names[i], roles[i])]
        cells += [data.cellphone()]
        bloods += [data.blood_type()]
        atts += [data.attendant(last_names[i])]
        cell_at += [data.cellphone()]
        mail_at += [data.personal_mail(atts[i][0], atts[i][-1])]
        degrees += [data.degree(roles[i])]
        strats += [data.stratum()]
        costs += [data.semester_cost(strats[i], roles[i])]
        enroles += [data.start_year(roles[i])]
        t_avg += [data.total_average(roles[i])]
        p_avg += [data.partial_average(roles[i], t_avg[i])]
        states += [data.degree_state(roles[i])]
        progs += [data.academic_program(degrees[i])]
        plans += [data.program_state(roles[i])]
        pens += [data.academic_plan(progs[i])]
        ctys += [data.living_city()]
        adds += [data.address(ctys[0])]
        sems += [data.semester(roles[i], states[i])]
        p_cred += [data.credits_percent(sems[i])]
        fins += [data.financing(roles[i])]
        fins_e += [data.fin_entity(fins[i])]
        fams += [data.family()]
        eng_lvls += [data.eng_lvl()]
        type_docs += [data.doc_type()]
        epss += [data.eps()]
        total_creds += [data.total_cred(degrees[i], roles[i])]
        ap_creds += [data.aprove_cred(total_creds[i], p_cred[i])]
        l_creds += [data.last_cred(total_creds[i], ap_creds[i])]
        ac_creds += [data.act_credits(roles[i])]
        armys += [data.army(genders[i])]
        allys += [data.allergy()]
        debts += [data.debt(costs[i], roles[i])]
        portal_ids += [data.portal_id(eci_nums[i], eci_ids)]
        cancell += [data.cancelled(sems[i], roles[i])]
        failed_set += [data.failed(sems[i], roles[i])]
        exp_years += [data.expected_year(enroles[i], roles[i])]
        countries += [data.birth_country()]
        b_cities += [data.birth_city(countries[i])]
        c_states += [data.civil_state()]
        monits += [data.monit(roles[i])]
    table["Documento de identidad"] = list_id
    table["# carnet"] = eci_nums
    table["Nombre"] = names
    table["Apellidos"] = last_names
    table["Genero"] = genders
    table["Edad"] = ages
    table["Correo personal"] = p_mails
    table["Cargo"] = roles
    table["Correo Ins"] = a_mails
    table["Telefono"] = cells
    table["Ciudad residencia"] = ctys
    table["Direccion residencia"] = adds
    table["Tipo de sangre"] = bloods
    table["Fecha nacimiento"] = births
    table["Acudiente"] = atts
    table["Tel. Acudiente"] = cell_at
    table["Correo acudiente"] = mail_at
    table["Carrera"] = degrees
    table["Programa academico"] = progs
    table["Plan acaemico"] = pens
    table["Estado Programa"] = plans
    table["Estado carrera"] = states
    table["Semestre"] = sems
    table["Matricula"] = costs
    table["Estrato"] = strats
    table["Año de admisión"] = enroles
    table["Promedio acumulado"] = t_avg
    table["Promedio semestre"] = p_avg
    table["% creditos aprovados"] = p_cred
    table["Financiado"] = fins
    table["Entidad que lo financia"] = fins_e
    table["Familiares en la Escuela"] = fams
    table["Nivel de ingles"] = eng_lvls
    table["Tipo documento"] = type_docs
    table["EPS"] = epss
    table["Total creditos"] = total_creds
    table["Creditos aprovados"] = ap_creds
    table["Creditos faltantes"] = l_creds
    table["Creditos actuales"] = ac_creds
    table["Libreta militar"] = armys
    table["Alergias"] = allys
    table["Deuda"] = debts
    table["ID Enlace"] = portal_ids
    table["Materias canceladas"] = cancell
    table["Materias perdidas"] = failed_set
    table["Año esperado de grado"] = exp_years
    table["Pais de nacimiento"] = countries
    table["Ciudad Nacimiento"] = b_cities
    table["Estado civil"] = c_states
    table["Monitor"] = monits
    table.to_csv("table.csv")
    table.to_excel("table.xlsx", index=False)
